org: dickey
app: mirky-api
service: mirky-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-domain-manager

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
	
custom:
  customDomain:
    domainName: api.mirky.app
    stage: dev
    basePath: v1
    certificateName: 'api.mirky.app'
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: false